# GitHub Sponsors configuration

github: [onetimesecret]

# Other funding platforms (uncomment and add if applicable)
# patreon: username
# open_collective: username
# ko_fi: username
# custom: ['https://example.com']
